# Generated by Django 2.1.9 on 2022-11-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20221105_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comments',
            field=models.TextField(verbose_name='E-Mail Address'),
        ),
    ]
