# Generated by Django 2.1.9 on 2022-11-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20221106_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='assignedTeacherId',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
