# Generated by Django 2.1.9 on 2022-11-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_review_assignedteacherid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='assignedTeacherId',
            field=models.CharField(choices=[('1', 'alan')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
