# Generated by Django 2.1.9 on 2022-11-06 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_auto_20221106_0527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='assignedDoctorId',
            new_name='assignedTeacherId',
        ),
    ]
