# Generated by Django 2.1.9 on 2022-11-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.IntegerField(null=True, verbose_name='Ratings'),
        ),
    ]
