# Generated by Django 2.1.9 on 2022-11-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_auto_20221106_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='clarity',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='loud',
            field=models.CharField(default='1', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='partiality',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='punctual',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='time',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
