# Generated by Django 2.1.9 on 2022-11-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_auto_20221106_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='sub',
            field=models.CharField(choices=[('1', 'Maths'), ('2', 'Chemistry'), ('3', 'Physics'), ('4', 'Biology'), ('4', 'Hindi')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
