# Generated by Django 2.1.9 on 2022-11-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_patient_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sub',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Hindi', 'Hindi')], max_length=100),
        ),
    ]
