# Generated by Django 2.1.9 on 2022-11-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0014_auto_20221106_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.AlterField(
            model_name='patient',
            name='clarity',
            field=models.IntegerField(max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='loud',
            field=models.IntegerField(max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='partiality',
            field=models.IntegerField(max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='punctual',
            field=models.IntegerField(max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='time',
            field=models.IntegerField(max_length=40),
        ),
    ]
