# Generated by Django 2.1.9 on 2022-11-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0015_auto_20221113_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='time',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], max_length=40),
        ),
    ]
