# Generated by Django 2.1.9 on 2022-11-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0016_auto_20221113_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='clarity',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='loud',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Ratings'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='partiality',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='punctual',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='time',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=40),
        ),
    ]
